# Permalinks
permalink:           pretty

# Setup
title:               'Machine Learning and Intelligent Systems'
url:                 https://malis-course.github.io/malis
tagline:             'MALIS - Fall 2023 Fri 13:30 - 16:45'
baseurl:             "https://malis-course.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

include:
  - _pages

# Cloudinary
#cloudinary:
#  cloud_name: your cloudinary username

# About/contact
author:
  name:              Maria A. Zuluaga
  url:               https://zuluaga.eurecom.io
  email:             

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/malis-course/malis
